name: pytest

on: [ push, pull_request ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt
      - name: Test with pytest
        id: pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          click-to-expand: false
          report-title: 'Wordsworth Testing'
      - name: Grab Coverage number
        run: |
          coverage_percentage=$(echo "${{ steps.pytest.outputs.summary }}" | awk -F'%' '{print $1}')
          echo "COVERAGE_PERCENTAGE=${coverage_percentage}" >> $GITHUB_ENV
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST2_SECRET }}
          gistID: e530f17b6f8744b1a720db17ebda376d
          filename: build.json
          label: Tests
          message: ${{ steps.pytest.outcome }}
          color: green


#      - name: Create Awesome Badge
#        uses: schneegans/dynamic-badges-action@v1.7.0
#        with:
#          auth: ${{ secrets.GITHUB_TOKEN }}
#          gistID: e530f17b6f8744b1a720db17ebda376d
#          filename: coverage.json
#          label: Coverage
#          message: ${{ env.COVERAGE }}
#          valColorRange: ${{ env.COVERAGE }}
#          maxColorRange: 90
#          minColorRange: 50
